### ISSUE TITLE
Your proxy sucks.

### ISSUE THREAD

**Issue by MadjikDotPng** [xfinitywebdev/rival-unblocker#3]
![Screenshot 2024-03-07 11 48 30 AM](https://github.com/xfinitywebdev/rival-unblocker/assets/89202835/0f3b19f7-4225-40ec-af56-090633eb5630)
What is this??

**Comment by broplswork** [comment]
cry about it and thats the particles

**Comment by broplswork** [comment]
and also fuck ur issue bitch
